export const DATA_URL = 'https://ffl-3-new.firebaseio.com/'

export const teamCodes = {
    'Manchester City': 1,
    'Liverpool FC': 2,
    'Chelsea FC': 3,
    'Tottenham Hotspur': 4,
    'Arsenal FC': 5,
    'Manchester United': 6,
    'Wolverhampton Wanderers': 7,
    'Everton FC': 8,
    'Leicester City': 9,
    'West Ham United': 10,
    'West Bromwich Albion': 11,
    'Crystal Palace': 12,
    'Newcastle United': 13,
    'Leeds United': 14,
    'Burnley FC': 15,
    'Southampton FC': 16,
    'Brighton & Hove Albion': 17,
    'Fulham FC': 18,
    'Sheffield United': 19,
    'Aston Villa': 20,
    'Paris Saint-Germain': 21,
    'LOSC Lille': 22,
    'Olympique Lyon': 23,
    'AS Saint-Étienne': 24,
    'Olympique Marseille': 25,
    'Montpellier HSC': 26,
    'OGC Nice': 27,
    'Stade Reims': 28,
    'Nîmes Olympique': 29,
    'Stade Rennais FC': 30,
    'RC Strasbourg Alsace': 31,
    'FC Nantes': 32,
    'SCO Angers': 33,
    'FC Girondins Bordeaux': 34,
    'RC Lens': 35,
    'FC Lorient': 36,
    'AS Monaco': 37,
    'FC Metz': 38,
    'Stade Brest 29': 39,
    'Dijon FCO': 40,
    'Juventus FC': 41,
    'SSC Napoli': 42,
    'Atalanta BC': 43,
    'Inter Milan': 44,
    'AC Milan': 45,
    'AS Roma': 46,
    'Torino FC': 47,
    'SS Lazio': 48,
    'UC Sampdoria': 49,
    'Bologna FC 1909': 50,
    'US Sassuolo': 51,
    'Udinese Calcio': 52,
    'FC Crotone': 53,
    'Parma Calcio 1913': 54,
    'Cagliari Calcio': 55,
    'ACF Fiorentina': 56,
    'Genoa CFC': 57,
    'Benevento Calcio': 58,
    'Brescia ???': 59,
    'Hellas Verona': 60,
    'FC Barcelona': 61,
    'Atlético Madrid': 62,
    'Real Madrid': 63,
    'Valencia CF': 64,
    'Getafe CF': 65,
    'Sevilla FC': 66,
    'Cádiz CF': 67,
    'Athletic Bilbao': 68,
    'Real Sociedad': 69,
    'Deportivo Alavés': 70,
    'Real Betis Balompié': 71,
    'SD Eibar': 72,
    'SD Huesca': 73,
    'Villarreal CF': 74,
    'Levante UD': 75,
    'Real Valladolid CF': 76,
    'Celta de Vigo': 77,
    'CA Osasuna': 78,
    'Granada CF': 79,
    'Mallorca': 80,
    'Bayern Munich': 81,
    'Borussia Dortmund': 82,
    'RB Leipzig': 83,
    'Bayer 04 Leverkusen': 84,
    'Borussia Mönchengladbach': 85,
    'VfL Wolfsburg': 86,
    'Eintracht Frankfurt': 87,
    'SV Werder Bremen': 88,
    'TSG 1899 Hoffenheim': 89,
    'Arminia Bielefeld': 90,
    'Hertha BSC': 91,
    '1.FSV Mainz 05': 92,
    'SC Freiburg': 93,
    'FC Schalke 04': 94,
    'FC Augsburg': 95,
    '1. FC Köln': 96,
    'VfB Stuttgart': 97,
    '1.FC Union Berlin': 98,
    'Ajax Amsterdam': 99,
    'PSV Eindhoven': 100,
    'Feyenoord Rotterdam': 101,
    'AZ Alkmaar': 102,
    'Vitesse Arnhem': 103,
    'FC Utrecht': 104,
    'Heracles Almelo': 105,
    'FC Groningen': 106,
    'ADO Den Haag': 107,
    'Willem II Tilburg': 108,
    'SC Heerenveen': 109,
    'VVV-Venlo': 110,
    'PEC Zwolle': 111,
    'FC Emmen': 112,
    'Fortuna Sittard': 113,
    'Twente Enschede FC': 114,
    'Sparta Rotterdam': 115,
    'RKC Waalwijk': 116,
    'Galatasaray SK': 117,
    'Istanbul Basaksehir FK': 118,
    'Besiktas JK': 119,
    'Trabzonspor': 120,
    'Büyüksehir Belediye Erzurumspor': 121,
    'Fenerbahce SK': 122,
    'Antalyaspor': 123,
    'Konyaspor': 124,
    'Alanyaspor': 125,
    'Hatayspor': 126,
    'Caykur Rizespor': 127,
    'Sivasspor': 128,
    'Fatih Karagümrük': 129,
    'Kasimpasa': 130,
    'Göztepe': 131,
    'Denizlispor': 132,
    'Genclerbirligi Ankara': 133,
    'Gaziantep FK': 134,
    'SL Benfica': 135,
    'FC Porto': 136,
    'Sporting CP': 137,
    'SC Braga': 138,
    'Vitória Guimarães SC': 139,
    'Moreirense FC': 140,
    'Rio Ave FC': 141,
    'Boavista Porto FC': 142,
    'Belenenses SAD': 143,
    'CD Santa Clara': 144,
    'CD Nacional': 145,
    'CS Marítimo': 146,
    'Vitória Setúbal FC': 147,
    'SC Farense': 148,
    'CD Tondela': 149,
    'FC Paços de Ferreira': 150,
    'FC Famalicão': 151,
    'Gil Vicente FC': 152
}
